Event at end of day bugfix + auto textcolor for events
Quivr/Android-Week-View pull request #30
Opened 2017-02-08 15:02 UTC by wietsebuseyne

Fixes #29 
Adds possibility to automatically select black or white as textcolor based on background color

2017-02-08 15:10 UTC, jhoobergs commented on library/src/main/java/com/alamkanak/weekview/WeekViewUtil.java
> +    public static int getTextColor(int color) {
I think this function shouldn't be included in the weekview. I think it should be possible to implement this method with an interface, so everyone can use it's own implementation.

2017-02-08 15:10 UTC, jhoobergs commented on library/src/main/java/com/alamkanak/weekview/WeekViewUtil.java
> +    public static int getTextColor(int color) {
@wietsebuseyne

2017-02-08 15:32 UTC, wietsebuseyne commented on library/src/main/java/com/alamkanak/weekview/WeekViewUtil.java
> +    public static int getTextColor(int color) {
You are right, I will change this

2017-02-08 15:57 UTC, wietsebuseyne commented
Added TextColorPicker interface to choose textcolor based on the event

2017-02-08 22:14 UTC, jhoobergs reviewed
@wietsebuseyne This seems ok, I'll test it during next week and then make a new release.

2017-02-14 10:45 UTC, jhoobergs requested changes
After changing my small comment, can you rebase your branch to the develop branch of this repo ?

2017-02-14 10:45 UTC, jhoobergs commented on library/src/main/java/com/alamkanak/weekview/WeekView.java
> +                minute -= Math.min(minute,  (mNewEventLengthInMinutes / 2));
I think this shouldn't always happen, this method is also used at other places where the length of new events doesn't make any difference.

2017-02-14 10:47 UTC, jhoobergs commented on library/src/main/java/com/alamkanak/weekview/WeekView.java
> +        if(textColorPicker != null) {
This if should be placed at line 554 or something, now it's set every time a title is drawn

2017-02-14 12:51 UTC, wietsebuseyne commented on library/src/main/java/com/alamkanak/weekview/WeekView.java
> +        if(textColorPicker != null) {
This is the desired behavior I think, as each event can require a different textColor (e.g. events with a dark background gets white text and events with a white background get black text)

If it is set in the init() function, all events will have the same text color.

2017-02-14 13:06 UTC, jhoobergs commented on library/src/main/java/com/alamkanak/weekview/WeekView.java
> +        if(textColorPicker != null) {
Yes, that's right. I was thinking about how to use it with the setTextColor methods, but that isn't possible. So this is right.

2017-02-14 14:45 UTC, wietsebuseyne commented
Rebased to merge the changes with the start- and endTime

2018-02-03 17:24 UTC, jhoobergs commented
See #78 (I rebased there and I'm fixing some other things)

2018-02-03 17:24 UTC, closed without merging