Fixed some problems with event displaying
Quivr/Android-Week-View pull request #54
Opened 2017-10-25 15:48 UTC by Skyost

Sometimes, events were not displayed when the rectangle was too small. This problem is now fixed.

2017-10-27 09:16 UTC, jhoobergs requested changes
Can you show some examples of things that went wrong and work with this change ?

2017-10-27 09:16 UTC, jhoobergs commented on library/src/main/java/com/alamkanak/weekview/WeekView.java
> -                    if (event.getId() != mNewEventId)
@Skyost You are missing this jf statement i guess ?

2017-10-27 16:11 UTC, Skyost commented
Hey,
I do not have an example, but sometimes when the event is too big for the screen, the text is getting completely ignored which gives an empty rectangle. You can test it with a small event and even on a regular screen.

2017-11-18 12:52 UTC, jhoobergs commented
@Skyost Can you create an artificial example and make a screenshot of it ?

2018-02-03 17:46 UTC, jhoobergs commented
I'm closing this issue because I haven't seen this happen. If you have this issue, please reopen it and provide an artificial example.

2018-02-03 17:46 UTC, closed without merging