Fixed scroll input lag
Quivr/Android-Week-View pull request #84
Opened 2018-04-02 19:06 UTC by Andrius-B

2018-04-02 19:55 UTC, Andrius-B commented
Illustrations of the problem before the fix:
![lag_show](https://user-images.githubusercontent.com/10669773/38213042-9c37a94e-36c8-11e8-89cc-f630fd47405a.gif)
_The view is supposed to allways move with the touch pointer, but there is a noticable lag in the input_

And with the fix it works as expected _(and feels way better)_
![no_lag_show](https://user-images.githubusercontent.com/10669773/38213041-9c1b85fc-36c8-11e8-898c-156ea32784e2.gif)

2018-04-06 14:40 UTC, jhoobergs requested changes

2018-04-06 14:40 UTC, jhoobergs commented on library/src/main/java/com/alamkanak/weekview/WeekView.java
> +            //goToNearestOrigin();
Remove this comment

2018-04-06 15:12 UTC, Andrius-B commented on library/src/main/java/com/alamkanak/weekview/WeekView.java
> +            //goToNearestOrigin();
Yep, removed it

2019-09-16 11:17 UTC, reilem commented
This PR is actually amazing. Sorry it took us this long to realise it. I will me merging and releasing today.

2019-09-16 11:17 UTC, merged